name: Chromatic
on: pull_request

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - name: chromatic
        run: npx chromatic -t 4a03d564ae85
      # - uses: chromaui/action-next@v1
      #   with:
      #     exitOnceUploaded: true
      #     onlyChanged: true
      #     traceChanged: true
      #     diagnostics: true
      #   env:
      #     CHROMATIC_PROJECT_TOKEN: 8709906d3258
      #     CHROMATIC_INDEX_URL: https://www.staging-chromatic.com/graphql
      - uses: actions/upload-artifact@v2
        with:
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log
